### PR TITLE
18 cucumber integration

### LINKED ISSUE #18: get cucumberjs in the sytem
replace integration test (currently story_routes_spec.js) with high level feature test

### PR DESCRIPTION
**Pull request by krauszraphael**
fixes #18 

Junior & Raphael paired to create base working Cucumber tests.

More refactoring needs to be done, but this is working for the moment.

### CODE REVIEW

**Comment by krauszraphael** [comment]
Please note that in this PR,
- to do cucumber tests: `npm run cucumber`
- to do mocha tests: `npm test`

**Comment by tansaku** [comment]
I guess we do also need to modify the travis file to run the cukes too ...

**Comment by krauszraphael** [comment]
@tansaku "not sure we needed to delete the vote stuff" - I wasn't aware we had - could you please elucidate?

**Comment by tansaku** [comment]
oh sorry @krauszraphael I was mis-intepreting the file diff - it has all the vote files in red - but actually I think they've just been touched and not changed - so this is ready to merge? It still have WIP in the title ...

**Comment by krauszraphael** [comment]
Yes, ready now. Thanks!

**Pull request merged**
